# Generated by Django 5.0.1 on 2025-11-03 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('uses_own_system', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('proximity', models.FloatField(default=1.0, help_text='Proximity from the nearest point of the poly line')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('driver_license', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(default=100)),
                ('cancellation_rate', models.FloatField(default=0.0)),
                ('double_booking_count', models.IntegerField(default=0)),
                ('strikes', models.IntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('trip_limit', models.IntegerField(default=2, help_text='Max concurrent trips for new operators')),
                ('payout_hold_hours', models.IntegerField(default=24, help_text='Hours to hold payout after trip')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('operator_admin', 'Operator Admin'), ('operator_staff', 'Operator Staff')], default='passenger', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('available_segments', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryMobileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(db_index=True)),
                ('planned_polyline', models.TextField()),
                ('planned_route_name', models.CharField(default='مسار غير معروف', max_length=100)),
                ('trip_type', models.CharField(choices=[('scheduled', 'Fixed Schedule'), ('flexible', 'Flexible Window')], default='scheduled', max_length=20)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
                ('departure_window_start', models.DateTimeField(blank=True, null=True)),
                ('departure_window_end', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('seat_matrix', models.JSONField(default=dict)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('planned_arrival', models.DateTimeField()),
                ('planned_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('distance_from_start_km', models.FloatField(default=0.0)),
                ('price_from_start', models.IntegerField(default=0)),
                ('passengers_boarded', models.IntegerField(default=0)),
                ('passengers_alighted', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fare', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('stripe', 'Stripe')], default='cash', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_source', models.CharField(choices=[('platform', 'Platform (Web/App)'), ('physical', 'Physical (By Operator)'), ('external_api', 'External API Partner')], default='platform', max_length=20)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_details', to='mishwari_main_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('bus_type', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('amenities', models.JSONField(default=dict)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='mishwari_main_app.busoperator')),
            ],
        ),
        migrations.AddConstraint(
            model_name='citylist',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='Unique Coordinates'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='operational_regions',
            field=models.ManyToManyField(to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='driver',
            name='buses',
            field=models.ManyToManyField(related_name='drivers', to='mishwari_main_app.bus'),
        ),
        migrations.AddField(
            model_name='driver',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.busoperator'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatormetrics',
            name='operator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='mishwari_main_app.busoperator'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.passenger'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(through='mishwari_main_app.BookingPassenger', to='mishwari_main_app.passenger'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.profile'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.seat'),
        ),
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.bus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver'),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='trip',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mishwari_main_app.busoperator'),
        ),
        migrations.AddField(
            model_name='trip',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mishwari_main_app.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mishwari_main_app.trip'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='mishwari_main_app.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_from', to='mishwari_main_app.tripstop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_to', to='mishwari_main_app.tripstop'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpassenger',
            unique_together={('booking', 'seat')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['from_city', 'to_city', 'journey_date'], name='mishwari_ma_from_ci_0647da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('trip', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'sequence'], name='mishwari_ma_trip_id_2ff48a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripstop',
            unique_together={('trip', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip', 'status'], name='mishwari_ma_trip_id_2b15d0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-booking_time'], name='mishwari_ma_user_id_16b802_idx'),
        ),
    ]
