# Generated by Django 5.0.1 on 2025-11-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='verification_documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='mishwari_ma_status_f62300_idx'),
        ),
    ]
