# Generated by Django 5.0.1 on 2025-11-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0003_upgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='busoperator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
