# Generated by Django 5.0.1 on 2025-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0005_bookingpassenger_age_bookingpassenger_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citylist',
            name='Unique Coordinates',
        ),
        migrations.RemoveField(
            model_name='citylist',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='citylist',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='citylist',
            name='proximity',
        ),
        migrations.AddField(
            model_name='citylist',
            name='waypoints',
            field=models.JSONField(default=list),
        ),
    ]
