# Generated by Django 5.2.8 on 2025-11-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0007_busoperator_platform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='busoperator',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='buses',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='mishwari_main_app.bus'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
