# Generated by Django 5.0.1 on 2025-11-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0008_alter_bus_is_verified_alter_busoperator_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='BookingPassenger',
        ),
    ]
