# Generated by Django 5.0.1 on 2025-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0010_booking_contact_email_booking_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mobile_number', 'last_attempt'], name='mishwari_ma_mobile__fcb2de_idx')],
            },
        ),
    ]
