# Generated by Django 5.0.1 on 2025-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0011_otpattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryMobileVerification',
        ),
        migrations.AlterField(
            model_name='otpattempt',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
