# Generated by Django 5.0.1 on 2025-11-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0012_delete_temporarymobileverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='security_pin',
            field=models.CharField(blank=True, help_text='Hashed 6-digit PIN for drivers', max_length=128, null=True),
        ),
    ]
