# Generated by Django 5.0.1 on 2025-12-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0014_driverinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_usb_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='avg_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operatormetrics',
            name='avg_response_time_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='operatormetrics',
            name='on_time_performance',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_trips', to='mishwari_main_app.bus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_trips', to='mishwari_main_app.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trips', to='mishwari_main_app.bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trips', to='mishwari_main_app.driver'),
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('bus_condition_rating', models.PositiveSmallIntegerField(help_text='AC, Seats, Cleanliness')),
                ('driver_rating', models.PositiveSmallIntegerField(help_text='Punctuality, Safety, Behavior')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mishwari_main_app.booking')),
                ('bus_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.bus')),
                ('driver_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver')),
                ('operator_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.busoperator')),
            ],
            options={
                'indexes': [models.Index(fields=['operator_snapshot', 'created_at'], name='mishwari_ma_operato_b7f7c9_idx')],
            },
        ),
    ]
