# Generated by Django 5.0.1 on 2025-12-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0015_bus_avg_rating_bus_has_ac_bus_has_usb_charging_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='amenities',
        ),
    ]
